- 
 name: install nginx 
 hosts: server
 become: yes
 tasks: 
  - name: install nginx
    apt: 
     name: nginx
     state: latest
  - name: start the nginx
    service: 
     name: nginx
     state: started
     enabled: yes
  - name: deploy the page
    copy: 
     src: index.html
     destination: /var/www/html/
